---
title: "Week 2: Simple Regression Model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=F)
```
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/391241/sp/39124100/embedIframeJs/uiconf_id/22119142/partner_id/391241?iframeembed=true&playerId=kaltura_player&entry_id=0_d28958g8&flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[hotspots.plugin]=1&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_e04h3r3e" width="720" height="480"  allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>


## Table of contents
1. [Ordinary Least Squares Derivation, Part I](2_1.html)
2. [Ordinary Least Squares Derivation, Part II](2_2.html)
3. [Ordinary Least Squares Derivation, Part III](2_3.html)
4. [OLS Algebraic Properties](2_4.html)
5. [Goodness of Fit](2_5.html)
6. [Coefficient Interpretation](2_6.html)
7. [OLS Statistical Properties, Part I](2_7.html)
8. [OLS Statistical Properties, Part II](2_8.html)
9. [Unbiasedness](2_9.html)
10. [OLS Variance](2_10.html)
11. [Homoscedasticity](2_11.html)
12. [Standard Errors](2_12.html)


---

[Begin](2_1.html)

