# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "https://michaeljerman.com/"
languageCode = "en-AU"
title = "Inequality"

  
# Hero section (from here on is for icon theme)
[params.main]
  title = "Economics of Inequality"
  term = "Winter, 2018"
  img = "images/shares.png"
  description = "Click on a section above to get started."
  weight = 1

  [[params.main.section]]
    title = "What&nbsp;is&nbsp;inequality?"
    weight = 2

    [[params.main.section.lecture]]
      title = "Introduction"
      slides = "slides/intro.html"
      print_slides = "slides/intro.pdf"
      # notes = "intro_notes.pdf"
      

  [[params.main.section]]
    title = "Causes"
    weight = 3

    [[params.main.section.lecture]]
      title = "To be added"
    
  [[params.main.section]]
    title = "Consequences"
    weight = 4

    [[params.main.section.lecture]]
      title = "To be added"

  [[params.main.section]]
    title = "Policy"
    weight = 5

    [[params.main.section.lecture]]
      title = "To be added"
