---
title: "Unbiasedness, Part II"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=F)
source(week3.R)
```

## Lecture Video

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/391241/sp/39124100/embedIframeJs/uiconf_id/22119142/partner_id/391241?iframeembed=true&playerId=kaltura_player&entry_id=0_d28958g8&flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[hotspots.plugin]=1&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=0_tvosr17u" width="720" height="480"  allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>



## Practice Question
Consider the model

$$wage = \beta_0 + \beta_1 educ + \beta_2 exper + u$$

If we were to estimate this model using the `wage2` dataset in R, would we expect $E(\widehat{\beta}_1) = \beta_1$?

<div id="spoiler" style="display:none">
Probably not---we would expect the OLS estimate of $\beta_1$ to be biased. There are likely many variables contained in $u$ that affect not only wage, but also an individual's education level. For instance, some people have more "ability," or "drive", than other people. High-ability people that are driven to succeed likely stay in school longer, on average, than people who are not as driven. Similarly, those same people are likely to work hard try to get ahead in the workplace, resulting in higher wages. But since we are not including this ability variable in our regression, assumption MLR4 will be violated and our estimates will be biased.
</div>

<button title="Click to Show/Hide Content" type="button" onclick="if(document.getElementById('spoiler') .style.display=='none') {document.getElementById('spoiler') .style.display=''}else{document.getElementById('spoiler') .style.display='none'}">Show/Hide Solution</button>


[Previous](3_5.html) | [Table of contents](3_0.html) | [Next](3_7.html)
