---
title: "Variance, Part I"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=F)
source(week3.R)
```

## Lecture Video

<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/391241/sp/39124100/embedIframeJs/uiconf_id/22119142/partner_id/391241?iframeembed=true&playerId=kaltura_player&entry_id=0_d28958g8&flashvars[localizationCode]=en&amp;flashvars[leadWithHTML5]=true&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[hotspots.plugin]=1&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=0_5a77ywv9" width="720" height="480"  allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="Kaltura Player"></iframe>


## Practice Question

Consider the following models:

1. $wage = \beta_0 + \beta_1 educ + \beta_2 exper + u$
2. $wage = \beta_0 + \beta_1 educ + \beta_2 exper + \beta_3 degrees + u$

The variable $degrees$ measures the number of educational degrees a person has earned. A high school graduate would have one degree, a college graduate would have 2 degrees (high school and college diplomas), etc. 

If we estimate both of the models using OLS, how would we expect the variance of the estimate for $\beta_1$ to change across models?


<div id="spoiler" style="display:none">
Years of education ($educ$) and the number of degrees a person has ($degrees$) are highly correlated. Most people that have a two degrees (high school plus college) have also gone to school more years than somebody who has just one degree. The variance inflation factor for $\beta_1$ in the second model would be very high, therefore causing the variance of the $\beta_1$ estimate in the second model to be higher than the variance in the first model.
</div>

<button title="Click to Show/Hide Content" type="button" onclick="if(document.getElementById('spoiler') .style.display=='none') {document.getElementById('spoiler') .style.display=''}else{document.getElementById('spoiler') .style.display='none'}">Show/Hide Solution</button>


[Previous](3_8.html) | [Table of contents](3_0.html) | [Next](3_10.html)
