#+OPTIONS: toc:nil num:nil 
#+REVEAL_TRANS: none

#+TITLE: Poverty and Credit
#+AUTHOR: ECON 383: Economics of Discrimination
#+DATE: Winter 2018

* The consumer's problem
- Economic models have optimizing consumers
- The "consumer's problem" is to maximize their lifetime utility:
$$\max_{\{c_t\}_{t=0}^T}~~ \sum_{t=0}^T \beta^t u(c_t)$$
- Consumers can save, borrow, invest in skills, etc to maximize well-being
- As $T\rightarrow \infty$, agents will end up consuming the same amount each period regardless of initial state ($t=0$)

* Initial conditions
- Consumers with lower initial state will invest in assets, skills to increase future consumption
- Initial state won't matter in the limit

* Optimal consumption path
- Each period ($t$), agents must decide how much to borrow (or save) and consume
- When optimizing, this is determined by /Euler equation/:
$$u'(c_t) = (1+r)\beta u'(c_{t+1})$$
- Optimizing agents /smooth/ their consumption
- Changes in (temporary) income will not affect consumption, simply save or borrow in response 

* Poverty and savings
- Many people who live in poverty lack access to formal savings instruments (banks, stocks, etc)
- Why is this the case? (Supply or demand?)

* Savings behavior
- We observe people living in poverty engaging in savings behavior
- Use extra income to buy bricks, make home larger (value is stored in home)
- ROSCA (rotating savings and credit associations)
  - Everyone puts money in a common pot every month 
  - Each month one person (rotating) gets the entire pot
- Common for people to belong to multiple ROSCA, other credit groups

* Supply side?
- Banks incur fixed costs with each new bank account (paperwork, regulatory overhead, etc)
- This is why many banks require minimum balances or charge a fee
- Fees can be much higher than balances that poor would like to save (income <$2/day)

* Dupas and Robinson
- RCT: Give rural Kenyans access to savings technologies (i.e. bank accounts)
- Most women use the accounts, most men do not
- Saving instrument allowed them to invest more in businesses, purchase more food for family
- Few people used account after a year
- Poor don't seem to take advantage of better savings opportunities when they become available!

* Example
- Banerjee and Duflo: Fruit vendors in Chennai, India borrow ~$50.00 each day for inventory, pay 4.69% interest /per day/
- Vendors also drink many cups of tea per day (~$0.10)
- Drinking 2 fewer cups for three days would mean they are debt free in 90 days
- Being debt-free would save them $2.00 per day
- Why?

* Example
- Duflo, Kremer, and Robinson: Farmers in western Kenya can invest in fertilizer, greatly increasing yields (and therefore profit)
- RCT: some farmers given fertilizer for free for a season, see yields increase
- Next year, 90% go back to not using fertilizer!
- Farmers report that they don't have enough savings when it becomes time to buy fertilizer again

* Behavioral economics of saving and spending
- People show /time inconsistency/ in their behavior
- Examples:
  - Pressing "snooze" too many times on the alarm
  - Asking someone to take a bag of chips away from you
  - Limiting the amount of cash you take out from the ATM
  - Casinos using chips instead of dollars (Disney dollars, gift cards, etc)

* Savings as a commitment device 
- Savings accounts allow you to bargain against your "future self"
- Putting money in an account is like "taking away the bag of chips"
- Offering people in poverty commitment devices (bank accounts that enforce self-imposed limits for withdraw or dates)  can increase savings considerably
- Savings increase for people who are simply offered account, regardless if they use it!
- With formal instruments, easy to take away the chips. Harder if you have to make the decision every day

* Example
- Duflo, Kremer, and Robinson: Kenyan farmers offered chance to buy fertilizer immediately after previous year's harvest
- Now 50% of farmers use fertilizer the next year
- Giving them the opportunity to buy in advance more effective than giving it to them for free!

* Arrow-Debreu economies
- In the Arrow-Debreu model, agents face risk and uncertainty
- /States/ occur with certain probabilities
- "Bad" states mean less income, "good" states mean more income
- Uncertainty can be aggregate (macroeconomic) or idiosyncratic (only affects individuals)

* State-contingent claims
- Arrow-Debreu agents can trade /state-contingent claims/ with one another
  - "If I get good state and you get a bad state, I agree to pay you if you do the same for me"
- Optimizing agents choose to fully insure against bad states (recall Euler equation)
- Idiosyncratic risk does not affect agents, only affected by aggregate risk 

* Poor vs rich state-contingent claims
- Rich people have many formal instruments to insure against idiosyncratic risk (unemployment insurance, health insurance, car insurance, savings accounts, social security, tax deductions, etc)
- Poor are also very good at insuring against risk, but lack access to formal instruments
- Risk-pools are smaller -- aggregate risk is greater
- Farmers can't buy fertilizer because expenses "come up": neighbor gets sick, you help them out
- Having money tied up in commitment device changes "on-hand" cash, changes "contracts" with family/neighbors

* Policy
- Formal credit opportunities make it less costly (economically and psychologically) to insure against idiosyncratic risk
- Access to developed financial systems allows risk to be spread more broadly, diminishing aggregate risk
  - Bad harvests affect Kenyan farmers much more severely than Iowan farmers
